version: '2.1'
services:
    dbuntu:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dbuntu
        volumes:
            - ~/.m2/:/root/.m2/
            - ~/loadrc/:/root/loadrc/
            - ~/loadrc/gitrc/.gitconfig:/root/.gitconfig
            - ./.bashrc:/root/.bashrc
            - ./var/logs/:/var/logs/
            - ./:/pkg-vim/
        command: /bin/sh -c "/pkg-vim/build.sh > /var/logs/containner.log 2>&1"
